# Batch Query Test Against Known-Pose Map

This notebook localizes test/query images against the known-pose reconstruction produced by `reconstruction_known_pose.ipynb`. Query images can come from any camera as long as their basenames exist in `metadata/poses.json`.

The map and query cameras do not need to share the same camera_name. Ground truth is matched by image basename.

## 1. Configuration

In [ ]:
from pathlib import Path
from datetime import datetime
import copy
import json
import random
import shutil

import numpy as np
import pandas as pd
import pycolmap
import torch

from hloc import extract_features, match_features, pairs_from_retrieval
from hloc.localize_sfm import QueryLocalizer, pose_from_cluster
from hloc.utils.parsers import parse_retrieval

from simulation_pose_utils import (
    image_basename,
    load_json,
    load_pose_records,
    metadata_pose_center,
    pycolmap_transform_rt,
    quat_wxyz_to_rotmat,
)

# Dataset with query metadata.
dataset_root = Path('../datasets/test_dataset_108_24_may')
intrinsics_json = dataset_root / 'metadata/intrinsics_pinhole.json'

# Query image folder. Can contain any camera as long as basenames exist in poses.json.
query_source_dir = dataset_root / 'test'
query_glob = '*.png'
max_queries = 200
random_seed = 42

# Known-pose map bundle created by reconstruction_known_pose.ipynb.
map_bundle_root = Path('../outputs/train_dataset_585_24_may-bundle')
sfm_model_root = map_bundle_root / 'sfm'
db_features = map_bundle_root / 'features.h5'
db_global_features = map_bundle_root / 'global-feats-netvlad.h5'

# Query outputs.
results_dir = map_bundle_root / 'query_batch_results_v4'
query_cache_dir = map_bundle_root / 'query_batch_v4_cache'
results_dir.mkdir(parents=True, exist_ok=True)
query_cache_dir.mkdir(parents=True, exist_ok=True)

# Localization parameters.
num_loc = 10
max_error = 12
# FIX: Always overwrite so cached stale features from partial runs don't cause silent skips.
overwrite_query_features = True

feature_conf = copy.deepcopy(extract_features.confs['superpoint_max'])
retrieval_conf = extract_features.confs['netvlad']
matcher_conf = match_features.confs['superpoint+lightglue']

# FIX: Verify GPU availability before running the pipeline.
gpu_available = torch.cuda.is_available()
print(f'CUDA available: {gpu_available}')
if gpu_available:
    print(f'GPU: {torch.cuda.get_device_name(0)}')
else:
    print('WARNING: No GPU detected. Running on CPU will be significantly slower.')

# Windows/sandbox-safe HLoc execution: avoid multiprocessing DataLoader workers.
# Keep class-compatible with Kornia's DataLoader[Any] annotation.
_original_dataloader = torch.utils.data.DataLoader
class _SingleProcessDataLoader(_original_dataloader):
    @classmethod
    def __class_getitem__(cls, item):
        return cls

    def __init__(self, *args, **kwargs):
        kwargs['num_workers'] = 0
        # FIX: Only disable pin_memory when there is no GPU; pin_memory speeds up GPU transfers.
        kwargs['pin_memory'] = torch.cuda.is_available()
        super().__init__(*args, **kwargs)
torch.utils.data.DataLoader = _SingleProcessDataLoader

for path in [query_source_dir, sfm_model_root, db_features, db_global_features]:
    if not path.exists():
        raise FileNotFoundError(path)

intrinsics_cfg = load_json(intrinsics_json)['cameras'][0]
print(f'Dataset: {dataset_root}')
print(f'Query dir: {query_source_dir}')
print(f'Map bundle: {map_bundle_root}')
print(f'SfM model: {sfm_model_root}')
print(f'Intrinsics: {intrinsics_cfg["model"]} {intrinsics_cfg["width"]}x{intrinsics_cfg["height"]} params={intrinsics_cfg["params"]}')

Dataset: ..\datasets\test_dataset_108_24_may
Query dir: ..\datasets\test_dataset_108_24_may\test
Map bundle: ..\outputs\train_dataset_585_24_may-bundle
SfM model: ..\outputs\train_dataset_585_24_may-bundle\sfm
Intrinsics: PINHOLE 1920x1080 params=[879.6779270567265, 879.6779270567265, 960.0, 540.0]

## 2. Load Map and Query Ground Truth

In [6]:
model = pycolmap.Reconstruction(sfm_model_root)
print(model.summary())

all_pose_records, pose_by_name, _ = load_pose_records(dataset_root, camera_names=None)
query_paths_all = sorted(p for p in query_source_dir.glob(query_glob) if p.is_file())
if max_queries is not None and max_queries < len(query_paths_all):
    rng = random.Random(random_seed)
    query_paths = sorted(rng.sample(query_paths_all, max_queries))
else:
    query_paths = query_paths_all

missing_metadata = [p.name for p in query_paths if p.name not in pose_by_name]
if missing_metadata:
    raise ValueError(f'{len(missing_metadata)} query images have no poses.json metadata. Examples: {missing_metadata[:10]}')

query_camera_distribution = {}
for p in query_paths:
    cam = pose_by_name[p.name]['camera_name']
    query_camera_distribution[cam] = query_camera_distribution.get(cam, 0) + 1

references = sorted(image.name for image in model.images.values())
print(f'All query images found: {len(query_paths_all)}')
print(f'Queries selected: {len(query_paths)}')
print(f'Random seed: {random_seed if max_queries is not None else None}')
print(f'Query camera distribution: {query_camera_distribution}')
print(f'Reference images in map: {len(references)}')

Reconstruction:
	num_rigs = 1
	num_cameras = 1
	num_frames = 585
	num_reg_frames = 585
	num_images = 585
	num_points3D = 190906
	num_observations = 755022
	mean_track_length = 3.95494
	mean_observations_per_image = 1290.64
	mean_reprojection_error = 1.29475
All query images found: 108
Queries selected: 108
Random seed: 42
Query camera distribution: {'front': 108}
Reference images in map: 585

## 3. Helper Functions

In [7]:
def extract_on_cpu(conf, image_root, image_list, feature_path, overwrite=True):
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    original = torch.cuda.is_available
    torch.cuda.is_available = lambda: False
    try:
        return extract_features.main(
            conf,
            image_root,
            image_list=image_list,
            feature_path=feature_path,
            overwrite=overwrite,
        )
    finally:
        torch.cuda.is_available = original


def resolve_reference_ids(model, names):
    ref_ids = []
    missing = []
    for name in names:
        image = model.find_image_with_name(name)
        if image is None:
            basename = image_basename(name)
            for candidate in model.images.values():
                if image_basename(candidate.name) == basename:
                    image = candidate
                    break
        if image is None:
            missing.append(name)
        else:
            ref_ids.append(image.image_id)
    if missing:
        raise ValueError('Retrieved images not registered in model: ' + ', '.join(missing))
    return ref_ids


CARLA_TO_COLMAP_S = np.array([
    [0.0, 1.0, 0.0],
    [0.0, 0.0, -1.0],
    [1.0, 0.0, 0.0],
], dtype=np.float64)
COLMAP_TO_CARLA_S = np.linalg.inv(CARLA_TO_COLMAP_S)


def wrap_angle_deg(angle):
    return ((float(angle) + 180.0) % 360.0) - 180.0


def heading_error_deg(est_heading, gt_heading):
    return abs(wrap_angle_deg(float(est_heading) - float(gt_heading)))


def colmap_world_to_camera_to_carla_yaw_deg(r_wc_rh):
    # PnP/pycolmap returns COLMAP right-handed world-to-camera rotation.
    # Convert it back to CARLA left-handed camera-to-world rotation before extracting yaw.
    r_cw_rh = np.asarray(r_wc_rh, dtype=np.float64).T
    r_cw_lh = COLMAP_TO_CARLA_S @ r_cw_rh @ CARLA_TO_COLMAP_S
    return wrap_angle_deg(np.degrees(np.arctan2(r_cw_lh[1, 0], r_cw_lh[0, 0])))


def metadata_record_to_carla_yaw_deg(record):
    r_wc_rh = quat_wxyz_to_rotmat([record['qw'], record['qx'], record['qy'], record['qz']])
    return colmap_world_to_camera_to_carla_yaw_deg(r_wc_rh)


metadata_yaw_errors = []
for query_path in query_paths:
    rec = pose_by_name[query_path.name]
    metadata_yaw_errors.append(heading_error_deg(metadata_record_to_carla_yaw_deg(rec), rec['yaw_deg']))
metadata_yaw_errors = np.array(metadata_yaw_errors, dtype=np.float64)
print('Metadata quaternion -> CARLA yaw sanity check')
print(f'  count: {len(metadata_yaw_errors)}')
print(f'  mean error: {metadata_yaw_errors.mean():.9f} deg')
print(f'  max error: {metadata_yaw_errors.max():.9f} deg')
if metadata_yaw_errors.max() >= 1e-3:
    raise AssertionError('Metadata quaternion to CARLA yaw conversion sanity check failed.')


localizer_conf = {
    'estimation': {'ransac': {'max_error': max_error}},
    'refinement': {'refine_focal_length': False, 'refine_extra_params': False},
}
localizer = QueryLocalizer(model, localizer_conf)
camera = pycolmap.Camera(
    model=intrinsics_cfg['model'],
    width=int(intrinsics_cfg['width']),
    height=int(intrinsics_cfg['height']),
    params=np.array(intrinsics_cfg['params'], dtype=float),
)

Metadata quaternion -> CARLA yaw sanity check
  count: 108
  mean error: 0.000002001 deg
  max error: 0.000009713 deg

## 4. Batch Query Localization

In [ ]:
import time
import numpy as np

localization_results = []
inference_times_ms = []

# ── PRE-STEP: Copy all query images to cache directory at once ────────────────
# FIX: Moved outside the loop to avoid blocking I/O on every iteration.
print('Copying query images to cache...')
for query_path in query_paths:
    dst = query_cache_dir / query_path.name
    if not dst.exists():
        shutil.copy2(query_path, dst)

all_query_rels = [f'{query_cache_dir.name}/{p.name}' for p in query_paths]
print(f'  {len(all_query_rels)} images ready in cache.')

# Shared H5 feature/match files for all queries.
# FIX: Single shared H5 per feature type instead of per-image files.
all_query_global_features = results_dir / 'query-global-feats-netvlad.h5'
all_query_features        = results_dir / 'query-features.h5'
all_query_matches         = results_dir / 'query-matches.h5'

# ── STEP 1: Extract global features for ALL queries in one call ───────────────
# FIX: Model (NetVLAD) is loaded ONCE here instead of once per image.
print('\nExtracting global features (NetVLAD) for all queries...')
t0 = time.perf_counter()
extract_features.main(
    retrieval_conf,
    map_bundle_root,
    image_list=all_query_rels,
    feature_path=all_query_global_features,
    overwrite=overwrite_query_features,
)
print(f'  Done in {(time.perf_counter() - t0)*1000:.0f} ms')

# ── STEP 2: Extract local features for ALL queries in one call ────────────────
# FIX: Model (SuperPoint) is loaded ONCE here instead of once per image.
print('\nExtracting local features (SuperPoint) for all queries...')
t0 = time.perf_counter()
extract_features.main(
    feature_conf,
    map_bundle_root,
    image_list=all_query_rels,
    feature_path=all_query_features,
    overwrite=overwrite_query_features,
)
print(f'  Done in {(time.perf_counter() - t0)*1000:.0f} ms')

# ── STEP 3: Per-image retrieval pairing + matching + PnP ─────────────────────
# Features are already extracted; the loop only does lightweight work per image.
print('\nRunning per-image retrieval, matching, and pose estimation...')

for idx, (query_path, query_rel) in enumerate(zip(query_paths, all_query_rels), start=1):
    query_basename = query_path.name
    query_gt = pose_by_name[query_basename]
    query_gt_center = metadata_pose_center(query_gt)

    stem = Path(query_basename).stem
    loc_pairs = results_dir / f'{stem}-pairs-query-netvlad.txt'

    print(f'\n[{idx}/{len(query_paths)}] {query_basename} camera={query_gt["camera_name"]}')

    try:
        start_time = time.perf_counter()

        # Retrieval: find top-N database images for this query.
        pairs_from_retrieval.main(
            descriptors=all_query_global_features,
            output=loc_pairs,
            num_matched=min(num_loc, len(references)),
            query_list=[query_rel],
            db_list=references,
            db_descriptors=db_global_features,
        )

        # Match local features between query and retrieved database images.
        # FIX: LightGlue matcher is loaded once per call; batching all pairs
        #      for this query minimises that overhead.
        match_features.main(
            matcher_conf,
            loc_pairs,
            features=all_query_features,
            features_ref=db_features,
            matches=all_query_matches,
            overwrite=True,
        )

        retrieval_dict  = parse_retrieval(loc_pairs)
        retrieved_names = retrieval_dict[query_rel]
        ref_ids         = resolve_reference_ids(model, retrieved_names)

        ret, log = pose_from_cluster(
            localizer, query_rel, camera, ref_ids,
            all_query_features, all_query_matches,
        )

        end_time   = time.perf_counter()
        elapsed_ms = (end_time - start_time) * 1000.0

        if ret is None:
            print('  pose estimation failed')
            localization_results.append({
                'image_name':  query_basename,
                'camera_name': query_gt['camera_name'],
                'success':     False,
                'error':       'pose_from_cluster returned None',
                'retrieved':   retrieved_names,
            })
            continue

        R_wc_rh, tvec    = pycolmap_transform_rt(ret['cam_from_world'])
        estimated_center = -R_wc_rh.T @ tvec
        position_error_m = float(np.linalg.norm(estimated_center - query_gt_center))

        estimated_heading = colmap_world_to_camera_to_carla_yaw_deg(R_wc_rh)
        gt_heading        = float(query_gt['yaw_deg'])
        heading_error     = heading_error_deg(estimated_heading, gt_heading)

        inference_times_ms.append(elapsed_ms)

        result = {
            'image_name':           query_basename,
            'camera_name':          query_gt['camera_name'],
            'capture_id':           int(query_gt['capture_id']),
            'success':              True,
            'num_inliers':          int(ret['num_inliers']),
            'position_error_m':     position_error_m,
            'estimated_center_x':   float(estimated_center[0]),
            'estimated_center_y':   float(estimated_center[1]),
            'estimated_center_z':   float(estimated_center[2]),
            'gt_center_x':          float(query_gt_center[0]),
            'gt_center_y':          float(query_gt_center[1]),
            'gt_center_z':          float(query_gt_center[2]),
            'estimated_heading_deg': estimated_heading,
            'ground_truth_yaw_deg': gt_heading,
            'heading_error_deg':    float(heading_error),
            'retrieved':            retrieved_names,
            'inference_time_ms':    elapsed_ms,
        }
        localization_results.append(result)
        print(f"  success inliers={result['num_inliers']} pos_err={position_error_m:.3f} m "
              f"heading_err={heading_error:.2f} deg time={elapsed_ms:.2f} ms")

    except Exception as exc:
        print(f'  error: {exc}')
        localization_results.append({
            'image_name':  query_basename,
            'camera_name': query_gt['camera_name'],
            'capture_id':  int(query_gt['capture_id']),
            'success':     False,
            'error':       str(exc),
        })

print('\nBatch localization finished')

if inference_times_ms:
    mean_time = np.mean(inference_times_ms)
    std_time  = np.std(inference_times_ms)
    min_time  = np.min(inference_times_ms)
    max_time  = np.max(inference_times_ms)
    print('\n--- Inference Time Metrics (retrieval + matching + PnP per image) ---')
    print(f'Mean Inference Time: {mean_time:.2f} ms')
    print(f'Std Deviation:       {std_time:.2f} ms')
    print(f'Min / Max Time:      {min_time:.2f} ms / {max_time:.2f} ms')

[2026/05/24 16:10:06 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

[2026/05/24 16:10:06 hloc INFO] Skipping the extraction.
[2026/05/24 16:10:06 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

[1/108] 000001_front_f00009863.png camera=front
Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.34s/it]
[2026/05/24 16:10:08 hloc INFO] Finished exporting features.
[2026/05/24 16:10:08 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:10:09 hloc INFO] Found 10 pairs.
[2026/05/24 16:10:09 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
c:\Users\ilker\Desktop\bitirme-project\venv38\lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
  0%|          | 0/10 [00:00<?, ?it/s]c:\Users\ilker\Desktop\bitirme-project\venv38\lib\site-packages\lightglue\lightglue.py:120: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  v = F.scaled_dot_product_attention(*args, attn_mask=mask).to(q.dtype)
100%|██████████| 10/10 [00:01<00:00,  9.59it/s]
[2026/05/24 16:10:11 hloc INFO] Finished exporting matches.
[2026/05/24 16:10:11 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2812 pos_err=0.028 m heading_err=0.14 deg

[2/108] 000002_front_f00009934.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:10:17 hloc INFO] Finished exporting features.
[2026/05/24 16:10:17 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.39s/it]
[2026/05/24 16:10:19 hloc INFO] Finished exporting features.
[2026/05/24 16:10:19 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:10:20 hloc INFO] Found 10 pairs.
[2026/05/24 16:10:20 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.71it/s]
[2026/05/24 16:10:21 hloc INFO] Finished exporting matches.
[2026/05/24 16:10:21 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1369 pos_err=0.056 m heading_err=0.04 deg

[3/108] 000003_front_f00010004.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.06s/it]
[2026/05/24 16:10:26 hloc INFO] Finished exporting features.
[2026/05/24 16:10:26 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.20s/it]
[2026/05/24 16:10:28 hloc INFO] Finished exporting features.
[2026/05/24 16:10:28 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:10:29 hloc INFO] Found 10 pairs.
[2026/05/24 16:10:29 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  8.38it/s]
[2026/05/24 16:10:30 hloc INFO] Finished exporting matches.
[2026/05/24 16:10:30 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1963 pos_err=0.017 m heading_err=0.04 deg

[4/108] 000004_front_f00010092.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.04s/it]
[2026/05/24 16:10:36 hloc INFO] Finished exporting features.
[2026/05/24 16:10:36 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.14s/it]
[2026/05/24 16:10:38 hloc INFO] Finished exporting features.
[2026/05/24 16:10:38 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:10:38 hloc INFO] Found 10 pairs.
[2026/05/24 16:10:38 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.52it/s]
[2026/05/24 16:10:40 hloc INFO] Finished exporting matches.
[2026/05/24 16:10:40 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=3594 pos_err=0.013 m heading_err=0.01 deg

[5/108] 000005_front_f00010178.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.12s/it]
[2026/05/24 16:10:45 hloc INFO] Finished exporting features.
[2026/05/24 16:10:45 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
[2026/05/24 16:10:47 hloc INFO] Finished exporting features.
[2026/05/24 16:10:47 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:10:48 hloc INFO] Found 10 pairs.
[2026/05/24 16:10:48 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.12it/s]
[2026/05/24 16:10:49 hloc INFO] Finished exporting matches.
[2026/05/24 16:10:49 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=3116 pos_err=0.081 m heading_err=0.00 deg

[6/108] 000006_front_f00010304.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:10:55 hloc INFO] Finished exporting features.
[2026/05/24 16:10:55 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.29s/it]
[2026/05/24 16:10:57 hloc INFO] Finished exporting features.
[2026/05/24 16:10:57 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:10:57 hloc INFO] Found 10 pairs.
[2026/05/24 16:10:57 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.31it/s]
[2026/05/24 16:10:59 hloc INFO] Finished exporting matches.
[2026/05/24 16:10:59 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1941 pos_err=0.358 m heading_err=0.01 deg

[7/108] 000007_front_f00010402.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
[2026/05/24 16:11:04 hloc INFO] Finished exporting features.
[2026/05/24 16:11:04 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
[2026/05/24 16:11:06 hloc INFO] Finished exporting features.
[2026/05/24 16:11:06 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:11:07 hloc INFO] Found 10 pairs.
[2026/05/24 16:11:07 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.72it/s]
[2026/05/24 16:11:08 hloc INFO] Finished exporting matches.
[2026/05/24 16:11:08 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1706 pos_err=0.124 m heading_err=0.00 deg

[8/108] 000008_front_f00010503.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:11:13 hloc INFO] Finished exporting features.
[2026/05/24 16:11:13 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:11:16 hloc INFO] Finished exporting features.
[2026/05/24 16:11:16 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:11:16 hloc INFO] Found 10 pairs.
[2026/05/24 16:11:16 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.98it/s]
[2026/05/24 16:11:17 hloc INFO] Finished exporting matches.
[2026/05/24 16:11:17 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=655 pos_err=0.020 m heading_err=0.02 deg

[9/108] 000009_front_f00010584.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
[2026/05/24 16:11:23 hloc INFO] Finished exporting features.
[2026/05/24 16:11:23 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.18s/it]
[2026/05/24 16:11:25 hloc INFO] Finished exporting features.
[2026/05/24 16:11:25 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:11:25 hloc INFO] Found 10 pairs.
[2026/05/24 16:11:25 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.66it/s]
[2026/05/24 16:11:26 hloc INFO] Finished exporting matches.
[2026/05/24 16:11:26 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=574 pos_err=0.067 m heading_err=0.03 deg

[10/108] 000010_front_f00010658.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.15s/it]
[2026/05/24 16:11:32 hloc INFO] Finished exporting features.
[2026/05/24 16:11:32 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
[2026/05/24 16:11:34 hloc INFO] Finished exporting features.
[2026/05/24 16:11:34 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:11:34 hloc INFO] Found 10 pairs.
[2026/05/24 16:11:34 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 14.80it/s]
[2026/05/24 16:11:35 hloc INFO] Finished exporting matches.
[2026/05/24 16:11:35 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=472 pos_err=0.019 m heading_err=0.02 deg

[11/108] 000011_front_f00010771.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:11:41 hloc INFO] Finished exporting features.
[2026/05/24 16:11:41 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
[2026/05/24 16:11:43 hloc INFO] Finished exporting features.
[2026/05/24 16:11:43 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:11:43 hloc INFO] Found 10 pairs.
[2026/05/24 16:11:43 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 16.98it/s]
[2026/05/24 16:11:44 hloc INFO] Finished exporting matches.
[2026/05/24 16:11:44 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=468 pos_err=0.007 m heading_err=0.02 deg

[12/108] 000012_front_f00011329.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
[2026/05/24 16:11:50 hloc INFO] Finished exporting features.
[2026/05/24 16:11:50 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.27s/it]
[2026/05/24 16:11:52 hloc INFO] Finished exporting features.
[2026/05/24 16:11:52 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:11:52 hloc INFO] Found 10 pairs.
[2026/05/24 16:11:52 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 15.15it/s]
[2026/05/24 16:11:53 hloc INFO] Finished exporting matches.
[2026/05/24 16:11:53 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1388 pos_err=0.010 m heading_err=0.01 deg

[13/108] 000013_front_f00011423.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
[2026/05/24 16:11:59 hloc INFO] Finished exporting features.
[2026/05/24 16:11:59 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.33s/it]
[2026/05/24 16:12:01 hloc INFO] Finished exporting features.
[2026/05/24 16:12:01 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:12:01 hloc INFO] Found 10 pairs.
[2026/05/24 16:12:01 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.90it/s]
[2026/05/24 16:12:02 hloc INFO] Finished exporting matches.
[2026/05/24 16:12:02 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1573 pos_err=0.009 m heading_err=0.00 deg

[14/108] 000014_front_f00011544.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
[2026/05/24 16:12:08 hloc INFO] Finished exporting features.
[2026/05/24 16:12:08 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
[2026/05/24 16:12:10 hloc INFO] Finished exporting features.
[2026/05/24 16:12:10 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:12:10 hloc INFO] Found 10 pairs.
[2026/05/24 16:12:10 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 14.76it/s]
[2026/05/24 16:12:11 hloc INFO] Finished exporting matches.
[2026/05/24 16:12:11 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1082 pos_err=0.012 m heading_err=0.02 deg

[15/108] 000015_front_f00011742.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.21s/it]
[2026/05/24 16:12:17 hloc INFO] Finished exporting features.
[2026/05/24 16:12:17 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.32s/it]
[2026/05/24 16:12:19 hloc INFO] Finished exporting features.
[2026/05/24 16:12:19 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:12:20 hloc INFO] Found 10 pairs.
[2026/05/24 16:12:20 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 14.81it/s]
[2026/05/24 16:12:21 hloc INFO] Finished exporting matches.
[2026/05/24 16:12:21 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=913 pos_err=0.051 m heading_err=0.01 deg

[16/108] 000016_front_f00011989.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.10s/it]
[2026/05/24 16:12:26 hloc INFO] Finished exporting features.
[2026/05/24 16:12:26 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
[2026/05/24 16:12:28 hloc INFO] Finished exporting features.
[2026/05/24 16:12:28 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:12:29 hloc INFO] Found 10 pairs.
[2026/05/24 16:12:29 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.18it/s]
[2026/05/24 16:12:30 hloc INFO] Finished exporting matches.
[2026/05/24 16:12:30 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2277 pos_err=0.068 m heading_err=0.02 deg

[17/108] 000017_front_f00012138.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.12s/it]
[2026/05/24 16:12:35 hloc INFO] Finished exporting features.
[2026/05/24 16:12:35 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.29s/it]
[2026/05/24 16:12:38 hloc INFO] Finished exporting features.
[2026/05/24 16:12:38 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:12:38 hloc INFO] Found 10 pairs.
[2026/05/24 16:12:38 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.32it/s]
[2026/05/24 16:12:39 hloc INFO] Finished exporting matches.
[2026/05/24 16:12:40 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1890 pos_err=0.015 m heading_err=0.02 deg

[18/108] 000018_front_f00012271.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.15s/it]
[2026/05/24 16:12:45 hloc INFO] Finished exporting features.
[2026/05/24 16:12:45 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
[2026/05/24 16:12:47 hloc INFO] Finished exporting features.
[2026/05/24 16:12:47 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:12:48 hloc INFO] Found 10 pairs.
[2026/05/24 16:12:48 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  8.79it/s]
[2026/05/24 16:12:49 hloc INFO] Finished exporting matches.
[2026/05/24 16:12:49 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1842 pos_err=0.043 m heading_err=0.01 deg

[19/108] 000019_front_f00012523.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:12:54 hloc INFO] Finished exporting features.
[2026/05/24 16:12:54 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
[2026/05/24 16:12:57 hloc INFO] Finished exporting features.
[2026/05/24 16:12:57 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:12:57 hloc INFO] Found 10 pairs.
[2026/05/24 16:12:57 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  8.67it/s]
[2026/05/24 16:12:59 hloc INFO] Finished exporting matches.
[2026/05/24 16:12:59 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1818 pos_err=0.063 m heading_err=0.02 deg

[20/108] 000020_front_f00012626.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
[2026/05/24 16:13:04 hloc INFO] Finished exporting features.
[2026/05/24 16:13:04 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.27s/it]
[2026/05/24 16:13:06 hloc INFO] Finished exporting features.
[2026/05/24 16:13:06 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:13:07 hloc INFO] Found 10 pairs.
[2026/05/24 16:13:07 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.41it/s]
[2026/05/24 16:13:08 hloc INFO] Finished exporting matches.
[2026/05/24 16:13:08 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=764 pos_err=0.066 m heading_err=0.04 deg

[21/108] 000021_front_f00012755.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.21s/it]
[2026/05/24 16:13:14 hloc INFO] Finished exporting features.
[2026/05/24 16:13:14 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
[2026/05/24 16:13:16 hloc INFO] Finished exporting features.
[2026/05/24 16:13:16 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:13:16 hloc INFO] Found 10 pairs.
[2026/05/24 16:13:16 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.16it/s]
[2026/05/24 16:13:18 hloc INFO] Finished exporting matches.
[2026/05/24 16:13:18 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1168 pos_err=0.019 m heading_err=0.01 deg

[22/108] 000022_front_f00012890.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
[2026/05/24 16:13:23 hloc INFO] Finished exporting features.
[2026/05/24 16:13:23 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:13:25 hloc INFO] Finished exporting features.
[2026/05/24 16:13:25 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:13:26 hloc INFO] Found 10 pairs.
[2026/05/24 16:13:26 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 16.06it/s]
[2026/05/24 16:13:27 hloc INFO] Finished exporting matches.
[2026/05/24 16:13:27 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=335 pos_err=0.023 m heading_err=0.03 deg

[23/108] 000023_front_f00012992.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.10s/it]
[2026/05/24 16:13:32 hloc INFO] Finished exporting features.
[2026/05/24 16:13:32 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
[2026/05/24 16:13:34 hloc INFO] Finished exporting features.
[2026/05/24 16:13:34 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:13:35 hloc INFO] Found 10 pairs.
[2026/05/24 16:13:35 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 17.54it/s]
[2026/05/24 16:13:35 hloc INFO] Finished exporting matches.
[2026/05/24 16:13:36 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=385 pos_err=0.032 m heading_err=0.03 deg

[24/108] 000024_front_f00013274.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
[2026/05/24 16:13:41 hloc INFO] Finished exporting features.
[2026/05/24 16:13:41 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.18s/it]
[2026/05/24 16:13:43 hloc INFO] Finished exporting features.
[2026/05/24 16:13:43 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:13:44 hloc INFO] Found 10 pairs.
[2026/05/24 16:13:44 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  8.19it/s]
[2026/05/24 16:13:45 hloc INFO] Finished exporting matches.
[2026/05/24 16:13:45 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1332 pos_err=0.086 m heading_err=0.02 deg

[25/108] 000025_front_f00013366.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:13:51 hloc INFO] Finished exporting features.
[2026/05/24 16:13:51 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.31s/it]
[2026/05/24 16:13:53 hloc INFO] Finished exporting features.
[2026/05/24 16:13:53 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:13:53 hloc INFO] Found 10 pairs.
[2026/05/24 16:13:53 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  8.54it/s]
[2026/05/24 16:13:55 hloc INFO] Finished exporting matches.
[2026/05/24 16:13:55 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2730 pos_err=0.002 m heading_err=0.01 deg

[26/108] 000026_front_f00013445.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
[2026/05/24 16:14:00 hloc INFO] Finished exporting features.
[2026/05/24 16:14:00 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
[2026/05/24 16:14:03 hloc INFO] Finished exporting features.
[2026/05/24 16:14:03 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:14:03 hloc INFO] Found 10 pairs.
[2026/05/24 16:14:03 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.85it/s]
[2026/05/24 16:14:04 hloc INFO] Finished exporting matches.
[2026/05/24 16:14:04 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=3035 pos_err=0.042 m heading_err=0.02 deg

[27/108] 000027_front_f00013528.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:14:10 hloc INFO] Finished exporting features.
[2026/05/24 16:14:10 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
[2026/05/24 16:14:12 hloc INFO] Finished exporting features.
[2026/05/24 16:14:12 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:14:12 hloc INFO] Found 10 pairs.
[2026/05/24 16:14:13 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.25it/s]
[2026/05/24 16:14:14 hloc INFO] Finished exporting matches.
[2026/05/24 16:14:14 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2867 pos_err=0.006 m heading_err=0.01 deg

[28/108] 000028_front_f00013648.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.12s/it]
[2026/05/24 16:14:19 hloc INFO] Finished exporting features.
[2026/05/24 16:14:19 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:14:22 hloc INFO] Finished exporting features.
[2026/05/24 16:14:22 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:14:22 hloc INFO] Found 10 pairs.
[2026/05/24 16:14:22 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.49it/s]
[2026/05/24 16:14:23 hloc INFO] Finished exporting matches.
[2026/05/24 16:14:24 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=3862 pos_err=0.013 m heading_err=0.01 deg

[29/108] 000029_front_f00013753.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
[2026/05/24 16:14:29 hloc INFO] Finished exporting features.
[2026/05/24 16:14:29 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.42s/it]
[2026/05/24 16:14:31 hloc INFO] Finished exporting features.
[2026/05/24 16:14:31 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:14:32 hloc INFO] Found 10 pairs.
[2026/05/24 16:14:32 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.41it/s]
[2026/05/24 16:14:33 hloc INFO] Finished exporting matches.
[2026/05/24 16:14:33 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2967 pos_err=0.027 m heading_err=0.01 deg

[30/108] 000030_front_f00013864.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
[2026/05/24 16:14:39 hloc INFO] Finished exporting features.
[2026/05/24 16:14:39 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
[2026/05/24 16:14:41 hloc INFO] Finished exporting features.
[2026/05/24 16:14:41 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:14:41 hloc INFO] Found 10 pairs.
[2026/05/24 16:14:41 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.39it/s]
[2026/05/24 16:14:43 hloc INFO] Finished exporting matches.
[2026/05/24 16:14:43 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=3422 pos_err=0.106 m heading_err=0.02 deg

[31/108] 000031_front_f00013980.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.07s/it]
[2026/05/24 16:14:48 hloc INFO] Finished exporting features.
[2026/05/24 16:14:48 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
[2026/05/24 16:14:50 hloc INFO] Finished exporting features.
[2026/05/24 16:14:50 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:14:51 hloc INFO] Found 10 pairs.
[2026/05/24 16:14:51 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  8.43it/s]
[2026/05/24 16:14:52 hloc INFO] Finished exporting matches.
[2026/05/24 16:14:52 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=164 pos_err=15.239 m heading_err=22.92 deg

[32/108] 000032_front_f00014091.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.12s/it]
[2026/05/24 16:14:58 hloc INFO] Finished exporting features.
[2026/05/24 16:14:58 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.27s/it]
[2026/05/24 16:15:00 hloc INFO] Finished exporting features.
[2026/05/24 16:15:00 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:15:00 hloc INFO] Found 10 pairs.
[2026/05/24 16:15:00 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.64it/s]
[2026/05/24 16:15:01 hloc INFO] Finished exporting matches.
[2026/05/24 16:15:02 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=638 pos_err=0.121 m heading_err=0.02 deg

[33/108] 000033_front_f00014226.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
[2026/05/24 16:15:07 hloc INFO] Finished exporting features.
[2026/05/24 16:15:07 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
[2026/05/24 16:15:09 hloc INFO] Finished exporting features.
[2026/05/24 16:15:09 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:15:10 hloc INFO] Found 10 pairs.
[2026/05/24 16:15:10 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.45it/s]
[2026/05/24 16:15:11 hloc INFO] Finished exporting matches.
[2026/05/24 16:15:11 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=764 pos_err=0.020 m heading_err=0.02 deg

[34/108] 000034_front_f00014319.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:15:16 hloc INFO] Finished exporting features.
[2026/05/24 16:15:16 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
[2026/05/24 16:15:18 hloc INFO] Finished exporting features.
[2026/05/24 16:15:18 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:15:19 hloc INFO] Found 10 pairs.
[2026/05/24 16:15:19 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 11.95it/s]
[2026/05/24 16:15:20 hloc INFO] Finished exporting matches.
[2026/05/24 16:15:20 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1180 pos_err=0.010 m heading_err=0.00 deg

[35/108] 000035_front_f00014474.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:15:25 hloc INFO] Finished exporting features.
[2026/05/24 16:15:25 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.34s/it]
[2026/05/24 16:15:28 hloc INFO] Finished exporting features.
[2026/05/24 16:15:28 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:15:28 hloc INFO] Found 10 pairs.
[2026/05/24 16:15:28 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 14.56it/s]
[2026/05/24 16:15:29 hloc INFO] Finished exporting matches.
[2026/05/24 16:15:29 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=661 pos_err=0.022 m heading_err=0.01 deg

[36/108] 000036_front_f00014674.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:15:35 hloc INFO] Finished exporting features.
[2026/05/24 16:15:35 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.18s/it]
[2026/05/24 16:15:37 hloc INFO] Finished exporting features.
[2026/05/24 16:15:37 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:15:37 hloc INFO] Found 10 pairs.
[2026/05/24 16:15:37 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.45it/s]
[2026/05/24 16:15:38 hloc INFO] Finished exporting matches.
[2026/05/24 16:15:38 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1873 pos_err=0.009 m heading_err=0.00 deg

[37/108] 000037_front_f00014859.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:15:44 hloc INFO] Finished exporting features.
[2026/05/24 16:15:44 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
[2026/05/24 16:15:46 hloc INFO] Finished exporting features.
[2026/05/24 16:15:46 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:15:46 hloc INFO] Found 10 pairs.
[2026/05/24 16:15:47 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  8.66it/s]
[2026/05/24 16:15:48 hloc INFO] Finished exporting matches.
[2026/05/24 16:15:48 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1420 pos_err=0.058 m heading_err=0.00 deg

[38/108] 000038_front_f00015009.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
[2026/05/24 16:15:53 hloc INFO] Finished exporting features.
[2026/05/24 16:15:53 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
[2026/05/24 16:15:56 hloc INFO] Finished exporting features.
[2026/05/24 16:15:56 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:15:56 hloc INFO] Found 10 pairs.
[2026/05/24 16:15:56 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 11.13it/s]
[2026/05/24 16:15:57 hloc INFO] Finished exporting matches.
[2026/05/24 16:15:57 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2212 pos_err=0.064 m heading_err=0.00 deg

[39/108] 000039_front_f00015118.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
[2026/05/24 16:16:03 hloc INFO] Finished exporting features.
[2026/05/24 16:16:03 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.30s/it]
[2026/05/24 16:16:05 hloc INFO] Finished exporting features.
[2026/05/24 16:16:05 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:16:06 hloc INFO] Found 10 pairs.
[2026/05/24 16:16:06 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 14.55it/s]
[2026/05/24 16:16:07 hloc INFO] Finished exporting matches.
[2026/05/24 16:16:07 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=999 pos_err=0.033 m heading_err=0.00 deg

[40/108] 000040_front_f00015242.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
[2026/05/24 16:16:12 hloc INFO] Finished exporting features.
[2026/05/24 16:16:12 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
[2026/05/24 16:16:14 hloc INFO] Finished exporting features.
[2026/05/24 16:16:14 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:16:15 hloc INFO] Found 10 pairs.
[2026/05/24 16:16:15 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.59it/s]
[2026/05/24 16:16:16 hloc INFO] Finished exporting matches.
[2026/05/24 16:16:16 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1678 pos_err=0.052 m heading_err=0.01 deg

[41/108] 000041_front_f00015345.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.11s/it]
[2026/05/24 16:16:21 hloc INFO] Finished exporting features.
[2026/05/24 16:16:21 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.17s/it]
[2026/05/24 16:16:23 hloc INFO] Finished exporting features.
[2026/05/24 16:16:23 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:16:24 hloc INFO] Found 10 pairs.
[2026/05/24 16:16:24 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.88it/s]
[2026/05/24 16:16:25 hloc INFO] Finished exporting matches.
[2026/05/24 16:16:25 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1866 pos_err=0.098 m heading_err=0.00 deg

[42/108] 000042_front_f00015448.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:16:30 hloc INFO] Finished exporting features.
[2026/05/24 16:16:30 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
[2026/05/24 16:16:33 hloc INFO] Finished exporting features.
[2026/05/24 16:16:33 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:16:33 hloc INFO] Found 10 pairs.
[2026/05/24 16:16:33 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 17.39it/s]
[2026/05/24 16:16:34 hloc INFO] Finished exporting matches.
[2026/05/24 16:16:34 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1365 pos_err=0.004 m heading_err=0.00 deg

[43/108] 000043_front_f00015641.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
[2026/05/24 16:16:39 hloc INFO] Finished exporting features.
[2026/05/24 16:16:39 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.20s/it]
[2026/05/24 16:16:41 hloc INFO] Finished exporting features.
[2026/05/24 16:16:41 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:16:42 hloc INFO] Found 10 pairs.
[2026/05/24 16:16:42 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 15.79it/s]
[2026/05/24 16:16:43 hloc INFO] Finished exporting matches.
[2026/05/24 16:16:43 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=941 pos_err=0.003 m heading_err=0.00 deg

[44/108] 000044_front_f00015809.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.11s/it]
[2026/05/24 16:16:48 hloc INFO] Finished exporting features.
[2026/05/24 16:16:48 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
[2026/05/24 16:16:50 hloc INFO] Finished exporting features.
[2026/05/24 16:16:50 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:16:51 hloc INFO] Found 10 pairs.
[2026/05/24 16:16:51 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 14.16it/s]
[2026/05/24 16:16:52 hloc INFO] Finished exporting matches.
[2026/05/24 16:16:52 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=246 pos_err=0.042 m heading_err=0.02 deg

[45/108] 000045_front_f00016052.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.12s/it]
[2026/05/24 16:16:57 hloc INFO] Finished exporting features.
[2026/05/24 16:16:57 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
[2026/05/24 16:16:59 hloc INFO] Finished exporting features.
[2026/05/24 16:16:59 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:17:00 hloc INFO] Found 10 pairs.
[2026/05/24 16:17:00 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 15.62it/s]
[2026/05/24 16:17:01 hloc INFO] Finished exporting matches.
[2026/05/24 16:17:01 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=436 pos_err=0.045 m heading_err=0.04 deg

[46/108] 000046_front_f00016193.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.20s/it]
[2026/05/24 16:17:06 hloc INFO] Finished exporting features.
[2026/05/24 16:17:06 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.12s/it]
[2026/05/24 16:17:08 hloc INFO] Finished exporting features.
[2026/05/24 16:17:08 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:17:09 hloc INFO] Found 10 pairs.
[2026/05/24 16:17:09 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.37it/s]
[2026/05/24 16:17:10 hloc INFO] Finished exporting matches.
[2026/05/24 16:17:10 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=606 pos_err=0.010 m heading_err=0.00 deg

[47/108] 000047_front_f00016307.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.10s/it]
[2026/05/24 16:17:15 hloc INFO] Finished exporting features.
[2026/05/24 16:17:15 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
[2026/05/24 16:17:17 hloc INFO] Finished exporting features.
[2026/05/24 16:17:17 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:17:18 hloc INFO] Found 10 pairs.
[2026/05/24 16:17:18 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 18.08it/s]
[2026/05/24 16:17:18 hloc INFO] Finished exporting matches.
[2026/05/24 16:17:18 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=758 pos_err=0.024 m heading_err=0.00 deg

[48/108] 000048_front_f00016411.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.11s/it]
[2026/05/24 16:17:24 hloc INFO] Finished exporting features.
[2026/05/24 16:17:24 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.15s/it]
[2026/05/24 16:17:26 hloc INFO] Finished exporting features.
[2026/05/24 16:17:26 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:17:26 hloc INFO] Found 10 pairs.
[2026/05/24 16:17:26 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 15.37it/s]
[2026/05/24 16:17:27 hloc INFO] Finished exporting matches.
[2026/05/24 16:17:27 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1487 pos_err=0.175 m heading_err=0.00 deg

[49/108] 000049_front_f00016508.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.23s/it]
[2026/05/24 16:17:33 hloc INFO] Finished exporting features.
[2026/05/24 16:17:33 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.35s/it]
[2026/05/24 16:17:35 hloc INFO] Finished exporting features.
[2026/05/24 16:17:35 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:17:36 hloc INFO] Found 10 pairs.
[2026/05/24 16:17:36 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.99it/s]
[2026/05/24 16:17:37 hloc INFO] Finished exporting matches.
[2026/05/24 16:17:37 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1341 pos_err=0.072 m heading_err=0.01 deg

[50/108] 000050_front_f00016651.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:17:42 hloc INFO] Finished exporting features.
[2026/05/24 16:17:42 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
[2026/05/24 16:17:45 hloc INFO] Finished exporting features.
[2026/05/24 16:17:45 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:17:45 hloc INFO] Found 10 pairs.
[2026/05/24 16:17:45 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 11.91it/s]
[2026/05/24 16:17:46 hloc INFO] Finished exporting matches.
[2026/05/24 16:17:46 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1115 pos_err=0.173 m heading_err=0.01 deg

[51/108] 000051_front_f00016730.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:17:52 hloc INFO] Finished exporting features.
[2026/05/24 16:17:52 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
[2026/05/24 16:17:54 hloc INFO] Finished exporting features.
[2026/05/24 16:17:54 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:17:54 hloc INFO] Found 10 pairs.
[2026/05/24 16:17:54 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.47it/s]
[2026/05/24 16:17:55 hloc INFO] Finished exporting matches.
[2026/05/24 16:17:55 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=668 pos_err=0.020 m heading_err=0.03 deg

[52/108] 000052_front_f00016926.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:18:01 hloc INFO] Finished exporting features.
[2026/05/24 16:18:01 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:18:03 hloc INFO] Finished exporting features.
[2026/05/24 16:18:03 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:18:03 hloc INFO] Found 10 pairs.
[2026/05/24 16:18:03 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.04it/s]
[2026/05/24 16:18:05 hloc INFO] Finished exporting matches.
[2026/05/24 16:18:05 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1558 pos_err=0.124 m heading_err=0.01 deg

[53/108] 000053_front_f00017025.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:18:10 hloc INFO] Finished exporting features.
[2026/05/24 16:18:10 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.33s/it]
[2026/05/24 16:18:13 hloc INFO] Finished exporting features.
[2026/05/24 16:18:13 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:18:13 hloc INFO] Found 10 pairs.
[2026/05/24 16:18:13 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.37it/s]
[2026/05/24 16:18:14 hloc INFO] Finished exporting matches.
[2026/05/24 16:18:15 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1704 pos_err=0.013 m heading_err=0.00 deg

[54/108] 000054_front_f00017140.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.10s/it]
[2026/05/24 16:18:20 hloc INFO] Finished exporting features.
[2026/05/24 16:18:20 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.20s/it]
[2026/05/24 16:18:22 hloc INFO] Finished exporting features.
[2026/05/24 16:18:22 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:18:22 hloc INFO] Found 10 pairs.
[2026/05/24 16:18:22 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.89it/s]
[2026/05/24 16:18:24 hloc INFO] Finished exporting matches.
[2026/05/24 16:18:24 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1559 pos_err=0.151 m heading_err=0.00 deg

[55/108] 000055_front_f00017202.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.45s/it]
[2026/05/24 16:18:30 hloc INFO] Finished exporting features.
[2026/05/24 16:18:30 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:03<00:00,  3.10s/it]
[2026/05/24 16:18:33 hloc INFO] Finished exporting features.
[2026/05/24 16:18:33 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:18:34 hloc INFO] Found 10 pairs.
[2026/05/24 16:18:34 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  5.58it/s]
[2026/05/24 16:18:36 hloc INFO] Finished exporting matches.
[2026/05/24 16:18:36 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2066 pos_err=0.180 m heading_err=0.00 deg

[56/108] 000056_front_f00017254.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.46s/it]
[2026/05/24 16:18:43 hloc INFO] Finished exporting features.
[2026/05/24 16:18:43 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:03<00:00,  3.17s/it]
[2026/05/24 16:18:46 hloc INFO] Finished exporting features.
[2026/05/24 16:18:46 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:18:47 hloc INFO] Found 10 pairs.
[2026/05/24 16:18:47 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  5.94it/s]
[2026/05/24 16:18:49 hloc INFO] Finished exporting matches.
[2026/05/24 16:18:49 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2146 pos_err=0.115 m heading_err=0.00 deg

[57/108] 000057_front_f00017314.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.41s/it]
[2026/05/24 16:18:57 hloc INFO] Finished exporting features.
[2026/05/24 16:18:57 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
[2026/05/24 16:19:01 hloc INFO] Finished exporting features.
[2026/05/24 16:19:01 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:19:01 hloc INFO] Found 10 pairs.
[2026/05/24 16:19:01 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  5.21it/s]
[2026/05/24 16:19:04 hloc INFO] Finished exporting matches.
[2026/05/24 16:19:04 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2160 pos_err=0.096 m heading_err=0.01 deg

[58/108] 000058_front_f00017398.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.44s/it]
[2026/05/24 16:19:11 hloc INFO] Finished exporting features.
[2026/05/24 16:19:11 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:03<00:00,  3.11s/it]
[2026/05/24 16:19:14 hloc INFO] Finished exporting features.
[2026/05/24 16:19:14 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:19:15 hloc INFO] Found 10 pairs.
[2026/05/24 16:19:15 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  5.07it/s]
[2026/05/24 16:19:17 hloc INFO] Finished exporting matches.
[2026/05/24 16:19:18 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2378 pos_err=0.036 m heading_err=0.01 deg

[59/108] 000059_front_f00017516.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.48s/it]
[2026/05/24 16:19:25 hloc INFO] Finished exporting features.
[2026/05/24 16:19:25 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:03<00:00,  3.08s/it]
[2026/05/24 16:19:28 hloc INFO] Finished exporting features.
[2026/05/24 16:19:28 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:19:28 hloc INFO] Found 10 pairs.
[2026/05/24 16:19:28 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  5.19it/s]
[2026/05/24 16:19:31 hloc INFO] Finished exporting matches.
[2026/05/24 16:19:31 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1700 pos_err=0.021 m heading_err=0.01 deg

[60/108] 000060_front_f00017597.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.48s/it]
[2026/05/24 16:19:38 hloc INFO] Finished exporting features.
[2026/05/24 16:19:38 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:03<00:00,  3.10s/it]
[2026/05/24 16:19:41 hloc INFO] Finished exporting features.
[2026/05/24 16:19:41 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:19:42 hloc INFO] Found 10 pairs.
[2026/05/24 16:19:42 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  6.74it/s]
[2026/05/24 16:19:44 hloc INFO] Finished exporting matches.
[2026/05/24 16:19:44 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=130 pos_err=0.121 m heading_err=0.00 deg

[61/108] 000061_front_f00017716.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:19:49 hloc INFO] Finished exporting features.
[2026/05/24 16:19:49 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
[2026/05/24 16:19:51 hloc INFO] Finished exporting features.
[2026/05/24 16:19:51 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:19:52 hloc INFO] Found 10 pairs.
[2026/05/24 16:19:52 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.25it/s]
[2026/05/24 16:19:53 hloc INFO] Finished exporting matches.
[2026/05/24 16:19:53 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1384 pos_err=0.007 m heading_err=0.00 deg

[62/108] 000062_front_f00017906.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
[2026/05/24 16:19:58 hloc INFO] Finished exporting features.
[2026/05/24 16:19:58 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.34s/it]
[2026/05/24 16:20:00 hloc INFO] Finished exporting features.
[2026/05/24 16:20:00 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:20:01 hloc INFO] Found 10 pairs.
[2026/05/24 16:20:01 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 19.28it/s]
[2026/05/24 16:20:02 hloc INFO] Finished exporting matches.
[2026/05/24 16:20:02 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=139 pos_err=0.025 m heading_err=0.08 deg

[63/108] 000063_front_f00018117.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
[2026/05/24 16:20:07 hloc INFO] Finished exporting features.
[2026/05/24 16:20:07 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.20s/it]
[2026/05/24 16:20:09 hloc INFO] Finished exporting features.
[2026/05/24 16:20:09 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:20:10 hloc INFO] Found 10 pairs.
[2026/05/24 16:20:10 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 11.48it/s]
[2026/05/24 16:20:11 hloc INFO] Finished exporting matches.
[2026/05/24 16:20:11 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1462 pos_err=0.014 m heading_err=0.00 deg

[64/108] 000064_front_f00018227.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:20:16 hloc INFO] Finished exporting features.
[2026/05/24 16:20:16 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.18s/it]
[2026/05/24 16:20:18 hloc INFO] Finished exporting features.
[2026/05/24 16:20:18 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:20:19 hloc INFO] Found 10 pairs.
[2026/05/24 16:20:19 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  8.78it/s]
[2026/05/24 16:20:20 hloc INFO] Finished exporting matches.
[2026/05/24 16:20:20 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1488 pos_err=0.033 m heading_err=0.01 deg

[65/108] 000065_front_f00018348.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.21s/it]
[2026/05/24 16:20:26 hloc INFO] Finished exporting features.
[2026/05/24 16:20:26 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
[2026/05/24 16:20:28 hloc INFO] Finished exporting features.
[2026/05/24 16:20:28 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:20:29 hloc INFO] Found 10 pairs.
[2026/05/24 16:20:29 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.20it/s]
[2026/05/24 16:20:30 hloc INFO] Finished exporting matches.
[2026/05/24 16:20:30 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=3443 pos_err=0.049 m heading_err=0.01 deg

[66/108] 000066_front_f00018479.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.20s/it]
[2026/05/24 16:20:35 hloc INFO] Finished exporting features.
[2026/05/24 16:20:35 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.29s/it]
[2026/05/24 16:20:38 hloc INFO] Finished exporting features.
[2026/05/24 16:20:38 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:20:38 hloc INFO] Found 10 pairs.
[2026/05/24 16:20:38 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.13it/s]
[2026/05/24 16:20:39 hloc INFO] Finished exporting matches.
[2026/05/24 16:20:40 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2532 pos_err=0.009 m heading_err=0.03 deg

[67/108] 000067_front_f00018594.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:20:45 hloc INFO] Finished exporting features.
[2026/05/24 16:20:45 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:20:47 hloc INFO] Finished exporting features.
[2026/05/24 16:20:47 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:20:48 hloc INFO] Found 10 pairs.
[2026/05/24 16:20:48 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.01it/s]
[2026/05/24 16:20:49 hloc INFO] Finished exporting matches.
[2026/05/24 16:20:49 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=934 pos_err=0.023 m heading_err=0.01 deg

[68/108] 000068_front_f00018726.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
[2026/05/24 16:20:54 hloc INFO] Finished exporting features.
[2026/05/24 16:20:54 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
[2026/05/24 16:20:56 hloc INFO] Finished exporting features.
[2026/05/24 16:20:56 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:20:57 hloc INFO] Found 10 pairs.
[2026/05/24 16:20:57 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.73it/s]
[2026/05/24 16:20:58 hloc INFO] Finished exporting matches.
[2026/05/24 16:20:58 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1094 pos_err=0.030 m heading_err=0.01 deg

[69/108] 000069_front_f00018868.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:21:03 hloc INFO] Finished exporting features.
[2026/05/24 16:21:03 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
[2026/05/24 16:21:06 hloc INFO] Finished exporting features.
[2026/05/24 16:21:06 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:21:06 hloc INFO] Found 10 pairs.
[2026/05/24 16:21:06 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.11it/s]
[2026/05/24 16:21:07 hloc INFO] Finished exporting matches.
[2026/05/24 16:21:07 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1849 pos_err=0.010 m heading_err=0.00 deg

[70/108] 000070_front_f00019005.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:21:13 hloc INFO] Finished exporting features.
[2026/05/24 16:21:13 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
[2026/05/24 16:21:15 hloc INFO] Finished exporting features.
[2026/05/24 16:21:15 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:21:15 hloc INFO] Found 10 pairs.
[2026/05/24 16:21:15 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.89it/s]
[2026/05/24 16:21:16 hloc INFO] Finished exporting matches.
[2026/05/24 16:21:17 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1291 pos_err=0.057 m heading_err=0.02 deg

[71/108] 000071_front_f00019116.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
[2026/05/24 16:21:22 hloc INFO] Finished exporting features.
[2026/05/24 16:21:22 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.27s/it]
[2026/05/24 16:21:24 hloc INFO] Finished exporting features.
[2026/05/24 16:21:24 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:21:25 hloc INFO] Found 10 pairs.
[2026/05/24 16:21:25 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.15it/s]
[2026/05/24 16:21:26 hloc INFO] Finished exporting matches.
[2026/05/24 16:21:26 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1558 pos_err=0.121 m heading_err=0.03 deg

[72/108] 000072_front_f00019195.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:21:31 hloc INFO] Finished exporting features.
[2026/05/24 16:21:31 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.30s/it]
[2026/05/24 16:21:33 hloc INFO] Finished exporting features.
[2026/05/24 16:21:33 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:21:34 hloc INFO] Found 10 pairs.
[2026/05/24 16:21:34 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.19it/s]
[2026/05/24 16:21:35 hloc INFO] Finished exporting matches.
[2026/05/24 16:21:35 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1426 pos_err=0.100 m heading_err=0.06 deg

[73/108] 000073_front_f00019320.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
[2026/05/24 16:21:40 hloc INFO] Finished exporting features.
[2026/05/24 16:21:40 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.33s/it]
[2026/05/24 16:21:43 hloc INFO] Finished exporting features.
[2026/05/24 16:21:43 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:21:43 hloc INFO] Found 10 pairs.
[2026/05/24 16:21:43 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 14.54it/s]
[2026/05/24 16:21:44 hloc INFO] Finished exporting matches.
[2026/05/24 16:21:44 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1511 pos_err=0.008 m heading_err=0.01 deg

[74/108] 000074_front_f00019427.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.21s/it]
[2026/05/24 16:21:49 hloc INFO] Finished exporting features.
[2026/05/24 16:21:49 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
[2026/05/24 16:21:52 hloc INFO] Finished exporting features.
[2026/05/24 16:21:52 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:21:52 hloc INFO] Found 10 pairs.
[2026/05/24 16:21:52 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.72it/s]
[2026/05/24 16:21:53 hloc INFO] Finished exporting matches.
[2026/05/24 16:21:53 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=234 pos_err=0.092 m heading_err=0.26 deg

[75/108] 000075_front_f00019616.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
[2026/05/24 16:21:59 hloc INFO] Finished exporting features.
[2026/05/24 16:21:59 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.33s/it]
[2026/05/24 16:22:01 hloc INFO] Finished exporting features.
[2026/05/24 16:22:01 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:22:02 hloc INFO] Found 10 pairs.
[2026/05/24 16:22:02 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.28it/s]
[2026/05/24 16:22:02 hloc INFO] Finished exporting matches.
[2026/05/24 16:22:03 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1226 pos_err=0.022 m heading_err=0.02 deg

[76/108] 000076_front_f00019810.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:22:08 hloc INFO] Finished exporting features.
[2026/05/24 16:22:08 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
[2026/05/24 16:22:10 hloc INFO] Finished exporting features.
[2026/05/24 16:22:10 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:22:11 hloc INFO] Found 10 pairs.
[2026/05/24 16:22:11 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 15.26it/s]
[2026/05/24 16:22:11 hloc INFO] Finished exporting matches.
[2026/05/24 16:22:12 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1700 pos_err=0.064 m heading_err=0.01 deg

[77/108] 000077_front_f00020482.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.21s/it]
[2026/05/24 16:22:17 hloc INFO] Finished exporting features.
[2026/05/24 16:22:17 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.34s/it]
[2026/05/24 16:22:19 hloc INFO] Finished exporting features.
[2026/05/24 16:22:19 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:22:20 hloc INFO] Found 10 pairs.
[2026/05/24 16:22:20 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.11it/s]
[2026/05/24 16:22:21 hloc INFO] Finished exporting matches.
[2026/05/24 16:22:21 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=444 pos_err=0.141 m heading_err=0.02 deg

[78/108] 000078_front_f00020588.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.10s/it]
[2026/05/24 16:22:26 hloc INFO] Finished exporting features.
[2026/05/24 16:22:26 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.18s/it]
[2026/05/24 16:22:28 hloc INFO] Finished exporting features.
[2026/05/24 16:22:28 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:22:29 hloc INFO] Found 10 pairs.
[2026/05/24 16:22:29 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.39it/s]
[2026/05/24 16:22:30 hloc INFO] Finished exporting matches.
[2026/05/24 16:22:30 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1047 pos_err=0.225 m heading_err=0.06 deg

[79/108] 000079_front_f00020661.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
[2026/05/24 16:22:35 hloc INFO] Finished exporting features.
[2026/05/24 16:22:35 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:22:37 hloc INFO] Finished exporting features.
[2026/05/24 16:22:37 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:22:38 hloc INFO] Found 10 pairs.
[2026/05/24 16:22:38 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.61it/s]
[2026/05/24 16:22:39 hloc INFO] Finished exporting matches.
[2026/05/24 16:22:39 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=606 pos_err=0.098 m heading_err=0.38 deg

[80/108] 000080_front_f00020762.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
[2026/05/24 16:22:45 hloc INFO] Finished exporting features.
[2026/05/24 16:22:45 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
[2026/05/24 16:22:47 hloc INFO] Finished exporting features.
[2026/05/24 16:22:47 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:22:47 hloc INFO] Found 10 pairs.
[2026/05/24 16:22:47 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 11.54it/s]
[2026/05/24 16:22:48 hloc INFO] Finished exporting matches.
[2026/05/24 16:22:48 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=689 pos_err=0.129 m heading_err=0.00 deg

[81/108] 000081_front_f00020844.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.15s/it]
[2026/05/24 16:22:54 hloc INFO] Finished exporting features.
[2026/05/24 16:22:54 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
[2026/05/24 16:22:56 hloc INFO] Finished exporting features.
[2026/05/24 16:22:56 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:22:56 hloc INFO] Found 10 pairs.
[2026/05/24 16:22:56 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.73it/s]
[2026/05/24 16:22:58 hloc INFO] Finished exporting matches.
[2026/05/24 16:22:58 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=464 pos_err=0.027 m heading_err=0.04 deg

[82/108] 000082_front_f00020932.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.15s/it]
[2026/05/24 16:23:03 hloc INFO] Finished exporting features.
[2026/05/24 16:23:03 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.29s/it]
[2026/05/24 16:23:05 hloc INFO] Finished exporting features.
[2026/05/24 16:23:05 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:23:06 hloc INFO] Found 10 pairs.
[2026/05/24 16:23:06 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.51it/s]
[2026/05/24 16:23:07 hloc INFO] Finished exporting matches.
[2026/05/24 16:23:07 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1284 pos_err=0.103 m heading_err=0.02 deg

[83/108] 000083_front_f00021107.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.12s/it]
[2026/05/24 16:23:12 hloc INFO] Finished exporting features.
[2026/05/24 16:23:12 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.35s/it]
[2026/05/24 16:23:15 hloc INFO] Finished exporting features.
[2026/05/24 16:23:15 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:23:15 hloc INFO] Found 10 pairs.
[2026/05/24 16:23:15 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 15.59it/s]
[2026/05/24 16:23:16 hloc INFO] Finished exporting matches.
[2026/05/24 16:23:16 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=662 pos_err=0.143 m heading_err=0.00 deg

[84/108] 000084_front_f00021272.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
[2026/05/24 16:23:21 hloc INFO] Finished exporting features.
[2026/05/24 16:23:21 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
[2026/05/24 16:23:24 hloc INFO] Finished exporting features.
[2026/05/24 16:23:24 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:23:24 hloc INFO] Found 10 pairs.
[2026/05/24 16:23:24 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.05it/s]
[2026/05/24 16:23:25 hloc INFO] Finished exporting matches.
[2026/05/24 16:23:25 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=199 pos_err=0.284 m heading_err=0.68 deg

[85/108] 000085_front_f00021388.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
[2026/05/24 16:23:31 hloc INFO] Finished exporting features.
[2026/05/24 16:23:31 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
[2026/05/24 16:23:33 hloc INFO] Finished exporting features.
[2026/05/24 16:23:33 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:23:33 hloc INFO] Found 10 pairs.
[2026/05/24 16:23:33 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 15.16it/s]
[2026/05/24 16:23:34 hloc INFO] Finished exporting matches.
[2026/05/24 16:23:34 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=205 pos_err=0.049 m heading_err=0.13 deg

[86/108] 000086_front_f00021492.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:23:40 hloc INFO] Finished exporting features.
[2026/05/24 16:23:40 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
[2026/05/24 16:23:42 hloc INFO] Finished exporting features.
[2026/05/24 16:23:42 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:23:42 hloc INFO] Found 10 pairs.
[2026/05/24 16:23:42 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 17.31it/s]
[2026/05/24 16:23:43 hloc INFO] Finished exporting matches.
[2026/05/24 16:23:43 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=673 pos_err=0.171 m heading_err=0.02 deg

[87/108] 000087_front_f00021692.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.15s/it]
[2026/05/24 16:23:49 hloc INFO] Finished exporting features.
[2026/05/24 16:23:49 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.37s/it]
[2026/05/24 16:23:51 hloc INFO] Finished exporting features.
[2026/05/24 16:23:51 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:23:51 hloc INFO] Found 10 pairs.
[2026/05/24 16:23:52 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.03it/s]
[2026/05/24 16:23:53 hloc INFO] Finished exporting matches.
[2026/05/24 16:23:53 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1136 pos_err=0.307 m heading_err=0.07 deg

[88/108] 000088_front_f00021878.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.08s/it]
[2026/05/24 16:23:58 hloc INFO] Finished exporting features.
[2026/05/24 16:23:58 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.36s/it]
[2026/05/24 16:24:00 hloc INFO] Finished exporting features.
[2026/05/24 16:24:00 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:24:01 hloc INFO] Found 10 pairs.
[2026/05/24 16:24:01 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.39it/s]
[2026/05/24 16:24:02 hloc INFO] Finished exporting matches.
[2026/05/24 16:24:02 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1899 pos_err=0.095 m heading_err=0.00 deg

[89/108] 000089_front_f00021970.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:24:08 hloc INFO] Finished exporting features.
[2026/05/24 16:24:08 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:24:10 hloc INFO] Finished exporting features.
[2026/05/24 16:24:10 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:24:10 hloc INFO] Found 10 pairs.
[2026/05/24 16:24:10 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.62it/s]
[2026/05/24 16:24:12 hloc INFO] Finished exporting matches.
[2026/05/24 16:24:12 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1981 pos_err=0.032 m heading_err=0.02 deg

[90/108] 000090_front_f00022045.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:24:17 hloc INFO] Finished exporting features.
[2026/05/24 16:24:17 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.27s/it]
[2026/05/24 16:24:19 hloc INFO] Finished exporting features.
[2026/05/24 16:24:19 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:24:20 hloc INFO] Found 10 pairs.
[2026/05/24 16:24:20 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.25it/s]
[2026/05/24 16:24:21 hloc INFO] Finished exporting matches.
[2026/05/24 16:24:21 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2636 pos_err=0.005 m heading_err=0.00 deg

[91/108] 000091_front_f00022143.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:24:26 hloc INFO] Finished exporting features.
[2026/05/24 16:24:26 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
[2026/05/24 16:24:28 hloc INFO] Finished exporting features.
[2026/05/24 16:24:28 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:24:29 hloc INFO] Found 10 pairs.
[2026/05/24 16:24:29 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.66it/s]
[2026/05/24 16:24:30 hloc INFO] Finished exporting matches.
[2026/05/24 16:24:30 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1835 pos_err=0.084 m heading_err=0.02 deg

[92/108] 000092_front_f00022253.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.15s/it]
[2026/05/24 16:24:36 hloc INFO] Finished exporting features.
[2026/05/24 16:24:36 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:24:38 hloc INFO] Finished exporting features.
[2026/05/24 16:24:38 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:24:38 hloc INFO] Found 10 pairs.
[2026/05/24 16:24:38 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.92it/s]
[2026/05/24 16:24:40 hloc INFO] Finished exporting matches.
[2026/05/24 16:24:40 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2005 pos_err=0.010 m heading_err=0.01 deg

[93/108] 000093_front_f00022375.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.14s/it]
[2026/05/24 16:24:45 hloc INFO] Finished exporting features.
[2026/05/24 16:24:45 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
[2026/05/24 16:24:47 hloc INFO] Finished exporting features.
[2026/05/24 16:24:47 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:24:48 hloc INFO] Found 10 pairs.
[2026/05/24 16:24:48 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.05it/s]
[2026/05/24 16:24:49 hloc INFO] Finished exporting matches.
[2026/05/24 16:24:49 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2450 pos_err=0.044 m heading_err=0.00 deg

[94/108] 000094_front_f00022473.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
[2026/05/24 16:24:55 hloc INFO] Finished exporting features.
[2026/05/24 16:24:55 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
[2026/05/24 16:24:57 hloc INFO] Finished exporting features.
[2026/05/24 16:24:57 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:24:57 hloc INFO] Found 10 pairs.
[2026/05/24 16:24:57 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.06it/s]
[2026/05/24 16:24:58 hloc INFO] Finished exporting matches.
[2026/05/24 16:24:59 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1884 pos_err=0.103 m heading_err=0.01 deg

[95/108] 000095_front_f00022645.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.24s/it]
[2026/05/24 16:25:04 hloc INFO] Finished exporting features.
[2026/05/24 16:25:04 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
[2026/05/24 16:25:06 hloc INFO] Finished exporting features.
[2026/05/24 16:25:06 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:25:07 hloc INFO] Found 10 pairs.
[2026/05/24 16:25:07 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.96it/s]
[2026/05/24 16:25:08 hloc INFO] Finished exporting matches.
[2026/05/24 16:25:08 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=334 pos_err=0.023 m heading_err=0.05 deg

[96/108] 000096_front_f00022945.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:25:13 hloc INFO] Finished exporting features.
[2026/05/24 16:25:13 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:25:15 hloc INFO] Finished exporting features.
[2026/05/24 16:25:15 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:25:16 hloc INFO] Found 10 pairs.
[2026/05/24 16:25:16 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.51it/s]
[2026/05/24 16:25:17 hloc INFO] Finished exporting matches.
[2026/05/24 16:25:17 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1438 pos_err=0.037 m heading_err=0.01 deg

[97/108] 000097_front_f00023031.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.20s/it]
[2026/05/24 16:25:23 hloc INFO] Finished exporting features.
[2026/05/24 16:25:23 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
[2026/05/24 16:25:25 hloc INFO] Finished exporting features.
[2026/05/24 16:25:25 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:25:25 hloc INFO] Found 10 pairs.
[2026/05/24 16:25:25 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.87it/s]
[2026/05/24 16:25:27 hloc INFO] Finished exporting matches.
[2026/05/24 16:25:27 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2452 pos_err=0.047 m heading_err=0.05 deg

[98/108] 000098_front_f00023113.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:25:32 hloc INFO] Finished exporting features.
[2026/05/24 16:25:32 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.31s/it]
[2026/05/24 16:25:35 hloc INFO] Finished exporting features.
[2026/05/24 16:25:35 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:25:35 hloc INFO] Found 10 pairs.
[2026/05/24 16:25:35 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.79it/s]
[2026/05/24 16:25:36 hloc INFO] Finished exporting matches.
[2026/05/24 16:25:36 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2974 pos_err=0.237 m heading_err=0.02 deg

[99/108] 000099_front_f00023212.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
[2026/05/24 16:25:42 hloc INFO] Finished exporting features.
[2026/05/24 16:25:42 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:25:44 hloc INFO] Finished exporting features.
[2026/05/24 16:25:44 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:25:44 hloc INFO] Found 10 pairs.
[2026/05/24 16:25:44 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.17it/s]
[2026/05/24 16:25:46 hloc INFO] Finished exporting matches.
[2026/05/24 16:25:46 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2690 pos_err=0.009 m heading_err=0.01 deg

[100/108] 000100_front_f00023303.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.11s/it]
[2026/05/24 16:25:51 hloc INFO] Finished exporting features.
[2026/05/24 16:25:51 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
[2026/05/24 16:25:53 hloc INFO] Finished exporting features.
[2026/05/24 16:25:53 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:25:54 hloc INFO] Found 10 pairs.
[2026/05/24 16:25:54 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.22it/s]
[2026/05/24 16:25:55 hloc INFO] Finished exporting matches.
[2026/05/24 16:25:55 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2942 pos_err=0.022 m heading_err=0.02 deg

[101/108] 000101_front_f00023380.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:26:01 hloc INFO] Finished exporting features.
[2026/05/24 16:26:01 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
[2026/05/24 16:26:03 hloc INFO] Finished exporting features.
[2026/05/24 16:26:03 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:26:03 hloc INFO] Found 10 pairs.
[2026/05/24 16:26:03 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:01<00:00,  9.60it/s]
[2026/05/24 16:26:05 hloc INFO] Finished exporting matches.
[2026/05/24 16:26:05 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=3155 pos_err=0.121 m heading_err=0.01 deg

[102/108] 000102_front_f00023459.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:26:10 hloc INFO] Finished exporting features.
[2026/05/24 16:26:10 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.29s/it]
[2026/05/24 16:26:12 hloc INFO] Finished exporting features.
[2026/05/24 16:26:12 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:26:13 hloc INFO] Found 10 pairs.
[2026/05/24 16:26:13 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 11.47it/s]
[2026/05/24 16:26:14 hloc INFO] Finished exporting matches.
[2026/05/24 16:26:14 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=909 pos_err=0.021 m heading_err=0.00 deg

[103/108] 000103_front_f00023575.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.15s/it]
[2026/05/24 16:26:19 hloc INFO] Finished exporting features.
[2026/05/24 16:26:19 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
[2026/05/24 16:26:22 hloc INFO] Finished exporting features.
[2026/05/24 16:26:22 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:26:22 hloc INFO] Found 10 pairs.
[2026/05/24 16:26:22 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 10.85it/s]
[2026/05/24 16:26:23 hloc INFO] Finished exporting matches.
[2026/05/24 16:26:23 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1304 pos_err=0.025 m heading_err=0.00 deg

[104/108] 000104_front_f00023657.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.11s/it]
[2026/05/24 16:26:29 hloc INFO] Finished exporting features.
[2026/05/24 16:26:29 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.35s/it]
[2026/05/24 16:26:31 hloc INFO] Finished exporting features.
[2026/05/24 16:26:31 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:26:31 hloc INFO] Found 10 pairs.
[2026/05/24 16:26:31 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 14.13it/s]
[2026/05/24 16:26:32 hloc INFO] Finished exporting matches.
[2026/05/24 16:26:32 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1350 pos_err=0.173 m heading_err=0.00 deg

[105/108] 000105_front_f00023747.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
[2026/05/24 16:26:38 hloc INFO] Finished exporting features.
[2026/05/24 16:26:38 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
[2026/05/24 16:26:40 hloc INFO] Finished exporting features.
[2026/05/24 16:26:40 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:26:40 hloc INFO] Found 10 pairs.
[2026/05/24 16:26:40 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 13.12it/s]
[2026/05/24 16:26:41 hloc INFO] Finished exporting matches.
[2026/05/24 16:26:42 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1467 pos_err=0.023 m heading_err=0.01 deg

[106/108] 000106_front_f00023852.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
[2026/05/24 16:26:47 hloc INFO] Finished exporting features.
[2026/05/24 16:26:47 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.30s/it]
[2026/05/24 16:26:49 hloc INFO] Finished exporting features.
[2026/05/24 16:26:49 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:26:50 hloc INFO] Found 10 pairs.
[2026/05/24 16:26:50 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 11.01it/s]
[2026/05/24 16:26:51 hloc INFO] Finished exporting matches.
[2026/05/24 16:26:51 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=1738 pos_err=0.008 m heading_err=0.01 deg

[107/108] 000107_front_f00023975.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.12s/it]
[2026/05/24 16:26:56 hloc INFO] Finished exporting features.
[2026/05/24 16:26:56 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
[2026/05/24 16:26:58 hloc INFO] Finished exporting features.
[2026/05/24 16:26:58 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:26:59 hloc INFO] Found 10 pairs.
[2026/05/24 16:26:59 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 11.70it/s]
[2026/05/24 16:27:00 hloc INFO] Finished exporting matches.
[2026/05/24 16:27:00 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}

  success inliers=2206 pos_err=0.108 m heading_err=0.02 deg

[108/108] 000108_front_f00024071.png camera=front

100%|██████████| 1/1 [00:01<00:00,  1.17s/it]
[2026/05/24 16:27:06 hloc INFO] Finished exporting features.
[2026/05/24 16:27:06 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}

Loaded SuperPoint model

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
[2026/05/24 16:27:08 hloc INFO] Finished exporting features.
[2026/05/24 16:27:08 hloc INFO] Extracting image pairs from a retrieval database.
[2026/05/24 16:27:08 hloc INFO] Found 10 pairs.
[2026/05/24 16:27:08 hloc INFO] Matching local features with configuration:
{'model': {'features': 'superpoint', 'name': 'lightglue'},
 'output': 'matches-superpoint-lightglue'}
100%|██████████| 10/10 [00:00<00:00, 12.33it/s]
[2026/05/24 16:27:09 hloc INFO] Finished exporting matches.

  success inliers=1448 pos_err=0.027 m heading_err=0.00 deg

Batch localization finished

## 5. Results Summary

In [9]:
results_df = pd.DataFrame(localization_results)
display(results_df)

successful = results_df[results_df['success'] == True]
failed = results_df[results_df['success'] != True]

summary = {
    'timestamp': datetime.now().isoformat(timespec='seconds'),
    'dataset_root': str(dataset_root),
    'query_source_dir': str(query_source_dir),
    'map_bundle_root': str(map_bundle_root),
    'sfm_model_root': str(sfm_model_root),
    'total_queries': int(len(results_df)),
    'successful_queries': int(len(successful)),
    'failed_queries': int(len(failed)),
    'success_rate': float(len(successful) / max(1, len(results_df))),
    'num_retrieved': num_loc,
    'ransac_max_error_px': max_error,
}

if len(successful) > 0:
    summary['position_error_m'] = {
        'mean': float(successful['position_error_m'].mean()),
        'median': float(successful['position_error_m'].median()),
        'max': float(successful['position_error_m'].max()),
    }
    summary['inliers'] = {
        'mean': float(successful['num_inliers'].mean()),
        'median': float(successful['num_inliers'].median()),
        'min': int(successful['num_inliers'].min()),
    }
    if 'heading_error_deg' in successful:
        summary['heading_error_deg'] = {
            'mean': float(successful['heading_error_deg'].mean()),
            'median': float(successful['heading_error_deg'].median()),
            'max': float(successful['heading_error_deg'].max()),
        }

print(json.dumps(summary, indent=2))

details_csv = results_dir / 'query_batch_details.csv'
summary_json = results_dir / 'query_batch_summary.json'
results_df.to_csv(details_csv, index=False)
summary_json.write_text(json.dumps(summary, indent=2), encoding='utf-8')

print(f'Details CSV: {details_csv}')
print(f'Summary JSON: {summary_json}')

,image_name,camera_name,capture_id,success,num_inliers,position_error_m,estimated_center_x,estimated_center_y,estimated_center_z,gt_center_x,gt_center_y,gt_center_z,estimated_heading_deg,ground_truth_yaw_deg,heading_error_deg,retrieved
0,000001_front_f00009863.png,front,1,True,2812,0.027528,-4.858079,-2.163367,9.883810,-4.885180,-2.167644,9.886053,104.995956,105.134682,0.138725,"[images/000059_front_f00007839.png, images/000..."
1,000002_front_f00009934.png,front,2,True,1369,0.056124,0.166685,-2.197539,11.316845,0.212937,-2.201335,11.348409,82.060521,82.105362,0.044841,"[images/000418_front_f00030357.png, images/000..."
2,000003_front_f00010004.png,front,3,True,1963,0.016881,7.310510,-2.192419,7.302847,7.320307,-2.200959,7.313620,123.934780,123.977325,0.042546,"[images/000065_front_f00008166.png, images/000..."
3,000004_front_f00010092.png,front,4,True,3594,0.012920,17.037124,-2.199846,0.756175,17.044885,-2.200731,0.745884,113.630770,113.623260,0.007509,"[images/000081_front_f00008999.png, images/000..."
4,000005_front_f00010178.png,front,5,True,3116,0.080702,25.988805,-2.200825,-3.059061,26.064013,-2.201399,-3.088324,112.457503,112.456123,0.001379,"[images/000090_front_f00009428.png, images/000..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,000104_front_f00023657.png,front,104,True,1350,0.173106,12.700512,-2.228350,29.466052,12.746348,-2.224928,29.632944,16.677131,16.673391,0.003740,"[images/000428_front_f00031038.png, images/000..."
104,000105_front_f00023747.png,front,105,True,1467,0.023262,18.782343,-2.205914,42.557880,18.787741,-2.201626,42.580097,26.730722,26.739618,0.008897,"[images/000435_front_f00031854.png, images/000..."
105,000106_front_f00023852.png,front,106,True,1738,0.007585,24.240497,-2.203837,52.209763,24.238360,-2.201675,52.202814,29.127933,29.133177,0.005244,"[images/000441_front_f00032477.png, images/000..."
106,000107_front_f00023975.png,front,107,True,2206,0.108131,30.063687,-2.205000,67.594486,30.087997,-2.201357,67.699786,10.431274,10.416160,0.015114,"[images/000454_front_f00033415.png, images/000..."
107,000108_front_f00024071.png,front,108,True,1448,0.027276,33.608694,-2.036149,76.375052,33.619942,-2.029819,76.399081,27.449898,27.450663,0.000765,"[images/000457_front_f00033740.png, images/000..."

{
  "timestamp": "2026-05-24T16:27:10",
  "dataset_root": "..\\datasets\\test_dataset_108_24_may",
  "query_source_dir": "..\\datasets\\test_dataset_108_24_may\\test",
  "map_bundle_root": "..\\outputs\\train_dataset_585_24_may-bundle",
  "sfm_model_root": "..\\outputs\\train_dataset_585_24_may-bundle\\sfm",
  "total_queries": 108,
  "successful_queries": 108,
  "failed_queries": 0,
  "success_rate": 1.0,
  "num_retrieved": 10,
  "ransac_max_error_px": 12,
  "position_error_m": {
    "mean": 0.2058140753712587,
    "median": 0.042237216143365106,
    "max": 15.238748478691798
  },
  "inliers": {
    "mean": 1517.7407407407406,
    "median": 1443.0,
    "min": 130
  },
  "heading_error_deg": {
    "mean": 0.24103370389217446,
    "median": 0.01196064654284612,
    "max": 22.91525806497623
  }
}
Details CSV: ..\outputs\train_dataset_585_24_may-bundle\query_batch_results_v2_24_may\query_batch_details.csv
Summary JSON: ..\outputs\train_dataset_585_24_may-bundle\query_batch_results_v2_24_may\query_batch_summary.json

## 6. VisualLocalization.net Threshold Format

In [10]:
benchmark_thresholds = [
    (0.25, 2.0),
    (0.50, 5.0),
    (5.00, 10.0),
]

total_queries = len(results_df)
successful_eval = successful.dropna(subset=['position_error_m', 'heading_error_deg']).copy()

benchmark_parts = []
benchmark_rows = []
for pos_thr, rot_thr in benchmark_thresholds:
    passed = successful_eval[
        (successful_eval['position_error_m'] <= pos_thr)
        & (successful_eval['heading_error_deg'] <= rot_thr)
    ]
    count = int(len(passed))
    percent_total = 100.0 * count / max(1, total_queries)
    percent_successful = 100.0 * count / max(1, len(successful_eval))
    benchmark_parts.append(f'{percent_total:.1f}')
    benchmark_rows.append({
        'position_threshold_m': pos_thr,
        'heading_threshold_deg': rot_thr,
        'passed': count,
        'total_queries': int(total_queries),
        'successful_evaluated_queries': int(len(successful_eval)),
        'percent_of_all_queries': percent_total,
        'percent_of_successful_queries': percent_successful,
    })

benchmark_df = pd.DataFrame(benchmark_rows)
print('VisualLocalization.net style localization scores')
print('All conditions: (0.25m, 2 deg) / (0.5m, 5 deg) / (5m, 10 deg)')
print('All conditions: ' + ' / '.join(benchmark_parts))
display(benchmark_df)

benchmark_json = results_dir / 'query_batch_visual_localization_thresholds.json'
benchmark_json.write_text(json.dumps(benchmark_rows, indent=2), encoding='utf-8')
print(f'Benchmark thresholds JSON: {benchmark_json}')

VisualLocalization.net style localization scores
All conditions: (0.25m, 2 deg) / (0.5m, 5 deg) / (5m, 10 deg)
All conditions: 96.3 / 99.1 / 99.1

,position_threshold_m,heading_threshold_deg,passed,total_queries,successful_evaluated_queries,percent_of_all_queries,percent_of_successful_queries
0,0.25,2.0,104,108,108,96.296296,96.296296
1,0.50,5.0,107,108,108,99.074074,99.074074
2,5.00,10.0,107,108,108,99.074074,99.074074

Benchmark thresholds JSON: ..\outputs\train_dataset_585_24_may-bundle\query_batch_results_v2_24_may\query_batch_visual_localization_thresholds.json

## 7. Worst Successful Queries

In [11]:
if len(successful) > 0:
    worst = successful.sort_values('position_error_m', ascending=False).head(10)
    display(worst[['image_name', 'camera_name', 'capture_id', 'num_inliers', 'position_error_m', 'heading_error_deg']])
else:
    print('No successful queries to inspect.')

if len(failed) > 0:
    print('Failed queries:')
    display(failed[['image_name', 'camera_name', 'capture_id', 'error']])

,image_name,camera_name,capture_id,num_inliers,position_error_m,heading_error_deg
30,000031_front_f00013980.png,front,31,164,15.238748,22.915258
5,000006_front_f00010304.png,front,6,1941,0.357704,0.013127
86,000087_front_f00021692.png,front,87,1136,0.307201,0.066383
83,000084_front_f00021272.png,front,84,199,0.284148,0.676066
97,000098_front_f00023113.png,front,98,2974,0.237491,0.021827
77,000078_front_f00020588.png,front,78,1047,0.225302,0.063068
54,000055_front_f00017202.png,front,55,2066,0.180429,0.000517
47,000048_front_f00016411.png,front,48,1487,0.174705,0.002403
49,000050_front_f00016651.png,front,50,1115,0.173112,0.008635
103,000104_front_f00023657.png,front,104,1350,0.173106,0.003740